### ISSUE TITLE
Licence link in readme 404s

### ISSUE THREAD

**Issue by andybak** [elraccoone/unity-promises#5]
Just out of curiosity - out of the multitude of well understood and vetted open source licences, was there really nothing that served your purpose? 

A lot of people will run a mile from something with a bespoke licence. Most people don't have a pet lawyer on hand to examine it and the risks are too high. 

> It it prohibited to distribute, sublicense, and/or sell copies of the Software!

The scary word there is "distribute". Can you clarify?

**Comment by jeffreylanters** [comment]
Hi, I've added the licence. I've forgot to add it to this repository. I see what you mean, on a second thought I might want to remove "Distribute" from that sentence. I really meant to make people aware they are free to use this and any of my modules in their (commercial) applications, but are not allow to sell or copy it somewhere such as the Unity Asset Store.

**Comment by andybak** [comment]
I think the problem is that nobody can safely use your software for one reason - you wrote your own licence and you're not a lawyer.

How about something like https://opensource.org/licenses/NPOSL-3.0

Or LGPL?

**Comment by jeffreylanters** [comment]
It's really just a slightly modified version of an existing licence. But you've got a very good point, I will look into it and change it as soon as possible!

**Comment by andybak** [comment]
> It's really just a slightly modified version of an existing licence.

That makes a difference. If you say something like "This is standard ABC with this extra clause" then it makes it much easier to understand for people with some existing understanding of standard licences.
